module.exports = {
  'qa-briteline20': {
    productUrl: 'https://qa-briteline20.supernovacompanies.com',
    cdnUrl: 'https://qa-cdn-snc.supernovacompanies.com',
    websiteCode: 'Briteline20',
    tenantId: 'ec2020',
    environment: 'qa',
  },
  'qa-ntw': {
    productUrl: 'https://ntw.qa.snc-dev.com',
    cdnUrl: 'https://qa-cdn-snc.supernovacompanies.com',
    websiteCode: 'SmartCredit',
    tenantId: 'ec273',
    environment: 'qa',
  },
  'qa-assetmark': {
    productUrl: 'https://assetmark.qa.snc-dev.com',
    cdnUrl: 'https://qa-cdn-snc.supernovacompanies.com',
    websiteCode: 'AssetMark',
    tenantId: 'ec273',
    environment: 'qa',
  },
  'qa-fcb': {
    productUrl: 'https://qa-ec2000.supernovacompanies.com',
    cdnUrl: 'https://qa-cdn-snc.supernovacompanies.com',
    websiteCode: 'fcb',
    tenantId: 'ec542',
    environment: 'qa',
  },
  'qa-wab': {
    productUrl: 'https://wab.qa.supernovacompanies.com',
    cdnUrl: 'https://qa-cdn-snc.supernovacompanies.com',
    websiteCode: 'wab',
    tenantId: 'ec233',
    environment: 'qa',
  },
  'dev-briteline20': {
    productUrl: 'https://cs-ec2020.snc-dev.com',
    cdnUrl: 'https://cs-cdn.snc-dev.com',
    websiteCode: 'Briteline20',
    tenantId: 'ec2020',
    environment: 'dev',
  },
  'dev-ntw': {
    productUrl: 'https://cs-ntw.snc-dev.com',
    cdnUrl: 'https://cs-cdn.snc-dev.com',
    websiteCode: 'SmartCredit',
    tenantId: 'ec273',
    environment: 'dev',
  },
  'dev-assetmark': {
    productUrl: 'https://cs-assetmark.snc-dev.com',
    cdnUrl: 'https://cs-cdn.snc-dev.com',
    websiteCode: 'AssetMark',
    tenantId: 'ec273',
    environment: 'dev',
  },
  'dev-briteline20-v2': {
    productUrl: 'https://cs-ec20202.snc-dev.com',
    cdnUrl: 'https://cs-cdn2.snc-dev.com',
    websiteCode: 'Briteline20',
    tenantId: 'ec2020',
    environment: 'dev-v2',
  },
  'dev-ntw-v2': {
    productUrl: 'https://cs-ntw2.snc-dev.com',
    cdnUrl: 'https://cs-cdn2.snc-dev.com',
    websiteCode: 'SmartCredit',
    tenantId: 'ec273',
    environment: 'dev-v2',
  },
  'dev-assetmark-v2': {
    productUrl: 'https://cs-assetmark2.snc-dev.com',
    cdnUrl: 'https://cs-cdn2.snc-dev.com',
    websiteCode: 'AssetMark',
    tenantId: 'ec273',
    environment: 'dev-v2',
  },
  'dev-wab-v2': {
    productUrl: 'https://cs-wab.snc-dev.com',
    cdnUrl: 'https://cs-wab.snc-dev.com',
    websiteCode: 'WAB',
    productCode: 'ec233',
    environment: 'dev-v2',
  },
  'qa-wab-v2': {
    productUrl: 'https://wab.qa.supernovacompanies.com',
    cdnUrl: 'https://wab.qa.supernovacompanies.com',
    websiteCode: 'WAB',
    productCode: 'ec233',
    environment: 'qa-v2',
  },
}
